### ISSUE TITLE
TAREAS QA TESTER

### ISSUE THREAD

**Issue by patrigarcia** [igrowker/i002-flowento-front#13]
1. Tomar notas sobre las funcionalidades y características de la plataforma.
2. Leer la documentación, familiarizarse con el flujo de usuario y las funcionalidades principales.
3. Desarrollar un plan de pruebas inicial que cubra las funcionalidades destacadas.
4. Incluir objetivos de las pruebas, alcance, criterios de entrada y salida.
5. Definir los entornos de prueba y las herramientas que se utilizarán.

**Comment by Carpentieri68** [comment]
Gracias Patricia!
